### PR TITLE
Feature/parallel queries

### PR DESCRIPTION
**Pull request by Levino**
- Improving and simplifying overall code base by using libraries instead of core nodejs functionality.
- Allowing queries in parallel

### CODE REVIEW

**Comment by JeremyCraigMartinez** [comment]
@Levino I was able to accomplish this by changing much less of the codebase under `lib/figo.js`. I would like for you to confirm that this fixes what you were having issues with before we merge it. Here is the branch comparison: https://github.com/figo-connect/node-figo/compare/feature/parallel

Please pay particular attention to the changes under `lib/parallel.js` with the [last three](https://github.com/figo-connect/node-figo/compare/feature/parallel#diff-3aee6616db49e2bfeb47d39f067b63edR59) `it` tests. We would prefer to stick with the implementation of `lib/figo.js` using the internal node.js `https` library rather than using more 3rd party libraries.

**Comment by Levino** [comment]
>  using the internal node.js https library rather than using more 3rd party libraries.

Okay, if this is a requirement, I have to pass. I will fork your repo then and maintain my own version.

Just out of curiosity: Why would you not want to use third party libraries. Please keep in mind that you are building your very own "third party library" here...

**Comment by JeremyCraigMartinez** [comment]
Well you make a good point, but we think it is a good idea to keep the internal libraries because as a convention this will prevent _our_ third party API from getting bloated and wasting clients time with additional `npm install`'s and disk space (as low as it may seem for superagent).

Additionally, the outcome of the existing code does not change at all from using `https` or `superagent`, so from the client's perspective it works all the same. As far as simplifying the code for open source contributions, you're totally right. However, by using the native `https` library, it makes the code more familiar to people coming from different perspectives and other third party libraries

**Comment by Levino** [comment]
Are you a node developer? Do you use npm on a regular basis?

1. ```npm install --save figo-node``` will install figo-node and all of its dependencies in one go! There is no need for "additional npm installs```. It would be a nightmare it there was. Same holds if figo-node is a dependency in the package.json. All dependencies are installed on ```npm install``` including all sub-dependencies. This is the beauty.

1. The library you are building is a server library. As one needs the "developer secret key" to use it, I cannot see any reasonable use case in the client going further than some tests or hacky dev tools. So you should not be concerned about disk space of "bloated libraries", nobody gives a nickle whether you use 200kb or 5 mb.

1. People are used to packages having dependencies. They actually prefer it. It has many reasons:
    1. One can pin-point bugs more easily.
    1. It is easy to fix something in the right place for good instead of debugging custom code in every repository.
    1. When it comes to security one should not reinvent the wheel. Don't build your own stuff. You will probably f**k it up.
    1. It is more important that your library makes a GOOD job, than an OKAY job but is "very very small". This absolute weird thing that the library cannot handle parallel requests is outright crazy! The reason why someone had these weird check implemented is because he did not want to use a library. So in the current case your approach of "we are the pure knights of the node" actually hindered you to build a good tool, but made you use clunky shortcuts.

So I stick with what I was saying. This library will always be a headache to use, to maintain and to contribute to if you refuse to allow the usage of some well tested and heavily used third party libraries. People should walk from it.

**Comment by JeremyCraigMartinez** [comment]
Again @Levino you make a good point, but there is a difference between reinventing the wheel and choosing to implement something yourself when all of the tools are readily available. Looking back to the [incident with left-pad](http://www.haneycodes.net/npm-left-pad-have-we-forgotten-how-to-program/)

> What concerns me here is that so many packages took on a dependency ... rather than taking 2 minutes to write such a basic function themselves.

The same opinion applies here. With the fix [here](https://github.com/figo-connect/node-figo/tree/feature/parallel), the problem is solved and the code is not too confusing to understand. We thank you very much for raising this issue and please don't hesitate to bring any other issues our way in the future

**Pull request closed without merging**
